### PR TITLE
Fix #48 and upgrade info buddy

### LINKED ISSUE #48: kpm_alloc allocate when all the memory is allocated
Actual behavior : When using `alloc` with a size which can't be allocated, `kpm_alloc` doesn't return a `-1` status code

Steps to reproduce : Launch `Nulix` with a qemu option to give 6M of memory, when in `$nsh` use alloc to allocate for 4M and ask a second time for another memory region

Expected behavior : `kmp_alloc` should return `-1` status code when it can't allocate enough memory when the memory is full close to be full

### PR DESCRIPTION
**Pull request by xlmod**
In bitmap_ffu, use a bitmap_t(uint8_t) variable to get the inverted byte and call __builtin_ffs.
The old way used a pointer and called `__builtin_ffs(~*cur)` that casted the value in 32bit so the __builtin_ffs returned a index bigger than the number of blocks.

Add to info buddy a optional arg to print the order.

Reset the color in alloc when allocation failed.

Closes #48

### CODE REVIEW

File: kernel/nsh/builtins/info.c [hunk 1]
```diff
@@ -62,13 +66,39 @@ static void info_idt() {
...
+		sb_set_color(sb_current, oldcolor);
+	}
+	sb_set_color(sb_current, oldcolor);
+	kprintf("\n");
+}
+
+static void info_buddy(int order) {
 	kprintf("INFO BUDDY\n");
 	kprintf("buddy address:        %p\n", buddy);
 	kprintf("buddy size:           %u KB\n", buddy->size / 1024);
```
Comment (mrxx0) [inline kernel/nsh/builtins/info.c:96]: I think we could check the value of ```buddy->size / 1024``` and if it equals 0 we should keep the size value in bytes or else keep it in kilobytes. This way the buddy print will be modular according to the system memory.

File: kernel/nsh/builtins/info.c [hunk 2]
```diff
@@ -62,13 +66,39 @@ static void info_idt() {
...
 	kprintf("orders address:       %p\n", buddy->orders[0].bitmap);
 	kprintf("frame number:         %x\n", buddy->nframes);
-	kprintf("memory size:          %u KB\n\n", buddy->nframes << 2);
+	kprintf("memory size:          %u KB\n", buddy->nframes << 2);
```
Comment (mrxx0) [inline kernel/nsh/builtins/info.c:99]: Same proposition for ```buddy->size``` should we always keep our memory size in kb ?

File: kernel/nsh/builtins/info.c [hunk 3]
```diff
@@ -103,7 +133,17 @@ int info(int argc, char **argv) {
 	} else if (!strcmp(argv[1], "stack")) {
 		info_stack();
 	} else if (!strcmp(argv[1], "buddy")) {
-		info_buddy();
+		if (argc > 2) {
+			char *ptr;
+			int order = strtol(argv[2], &ptr, 0);
+			if (*ptr || order < 0 || order >= KPM_NORDERS) {
+				kprintf(BLTNAME ": order number wrong.\n");
```
Comment (mrxx0) [inline kernel/nsh/builtins/info.c]: Maybe add a more precise usage message, something like : ``` order number not formatted correctly```

**Review by mrxx0 — COMMENTED** [review]
Some comments on global print value details and usage.

File: kernel/memory/kpm.c [hunk 4]
```diff
@@ -58,8 +58,8 @@ void kpm_init(struct multiboot_mmap_entry *entries, size_t count, size_t memkb)
 			kpm_enable((void *)(uintptr_t)entry->addr, (uint32_t)(entry->len));
 	}
 	kpm_disable((void *)0, PAGE_SIZE); // Also disables IDT + GDT by design
-	kpm_disable(&sk, (void *)(&ek - KERNEL_VIRT_OFFSET) - (void *)&sk);
-	kpm_disable(buddy - KERNEL_VIRT_OFFSET, buddy->size);
+	kpm_disable(&sk, ((uintptr_t)&ek - KERNEL_VIRT_OFFSET) - (uintptr_t)&sk);
+	kpm_disable((void *)((uintptr_t)buddy - KERNEL_VIRT_OFFSET), buddy->size);
```
Comment (e2r3p13) [inline kernel/memory/kpm.c:62]: Why are you sending a `uintptr_t` as the first argument of `kpm_disable` the first time and a `void *` the second time?

File: kernel/nsh/builtins/info.c (hunk 1 above)
Comment (lfalkau) [reply kernel/nsh/builtins/info.c:96]: Agree

File: kernel/memory/kpm.c (hunk 4 above)
Comment (xlmod) [reply kernel/memory/kpm.c:62]: because it's not the same argument number

File: kernel/nsh/builtins/info.c (hunk 1 above)
Comment (xlmod) [reply kernel/nsh/builtins/info.c:96]: ok but is not really important right now, make an issue.

Comment (e2r3p13) [reply kernel/nsh/builtins/info.c:96]: “The Devil is in the details, but so is salvation.”
― Hyman G. Rickover

Comment (mrxx0) [reply kernel/nsh/builtins/info.c:96]: OK I got it but....

image

**Review by e2r3p13 — APPROVED** [review]
