### PR TITLE
KPM: Add check of limit on enable/disable and fix bug

### LINKED ISSUE #43: KPM: enable/disable memory zone outside available memory
Missing check in kpm_enable and kpm_disable if the memory zone we try to enable/disable is outside the available memory, and have for effect to write outside the enabled_frames and override the orders bitmaps.

### PR DESCRIPTION
**Pull request by xlmod**
Check if the base + limit is not outside the memory available if is the case shrink the limit.

Remove a divide by 8 to calculate the enabled_frames_size because it's already done in the KPM_BYTES_FROM_BITS macro.

Closes #43

### CODE REVIEW

File: kernel/memory/kpm.c [hunk 1]
```diff
@@ -49,22 +49,22 @@ void kpm_init(struct multiboot_mmap_entry *entries, size_t count, size_t memkb)
 
 	buddy = (buddy_t *)ALIGNNEXT((uint32_t)&ek, PAGE_SIZE);
 	buddy->nframes = ALIGN(memkb * 1024 / PAGE_SIZE, 1024);
-	enabled_frames_size = KPM_NBYTES_FROM_NBITS(buddy->nframes / 8);
-	orders_size = 0;
+	enabled_frames_size = KPM_NBYTES_FROM_NBITS(buddy->nframes);
+	total_orders_size = 0;
```
Comment (mrxx0) [inline kernel/memory/kpm.c:53]: ```total_orders_size``` is undeclared creating a compilation error

**Review by mrxx0 — CHANGES_REQUESTED** [review]

**Review by mrxx0 — APPROVED** [review]
LGTM
